In [66]:
# for working part
import numpy as np
import pandas as pd


# for ml
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score,recall_score,f1_score,roc_auc_score

In [67]:
# reading the parquet file created in notebook 2

lead_conversion_data = pd.read_parquet("C:\\Users\\hp5cd\\OneDrive\\Desktop\\Python\\lead-conversion-prediction\\data\\processed_data.parquet")

In [68]:
# extracting important columns for this model
# as this will be used when creating leads we will have columns only that can be there after creating leads (x1)
# and when assigned we will have the columns that are in x2 


x1 = lead_conversion_data[['lead_source']]
x2 = lead_conversion_data[['lead_source','owner','assigned_month','assigned_year']]

y = lead_conversion_data['converted']


In [69]:
## stratify is used to keep the distribution of output variables same in test and train split
## test size 0.2 means 80% training split of data and 20% will be in test split


x1_train, x1_test, y1_train, y1_test = train_test_split(x1,y,random_state=42,test_size=0.2,stratify=y)

x2_train, x2_test, y2_train, y2_test = train_test_split(x2,y,random_state=42,test_size=0.2,stratify=y)

In [70]:
# categorical columns

categorical_x1 = ['lead_source']
categorical_x2 = ['lead_source','owner','assigned_month','assigned_year']

In [71]:
# preprocessing

preprocessor1 = ColumnTransformer(transformers=[('cat',OneHotEncoder(handle_unknown = 'ignore'),categorical_x1)])

# models
models = {'LR':LogisticRegression(max_iter=1000),'RF':RandomForestClassifier(random_state=42),'XGB': XGBClassifier()}


# pipeline with multiple model

for name,model in models.items():
    pipeline = Pipeline([
                        ('preprocessor', preprocessor1),
                         ('model', model)
                         ])
    
    pipeline.fit(x1_train,y1_train)

    y1_pred = pipeline.predict(x1_test)
    y1_pred_prob = pipeline.predict_proba(x1_test)[:,1]
    
    print("model", name)

    print(" ")
    print("accuracy_score: ", accuracy_score(y1_test,y1_pred))
    print("confusion_matrix: ", confusion_matrix(y1_test,y1_pred))
    print("precision_score: ", precision_score(y1_test,y1_pred))
    print("recall_score: ", recall_score(y1_test,y1_pred))
    print("f1_score: ", f1_score(y1_test,y1_pred))
    print("roc_auc_score: ", roc_auc_score(y1_test,y1_pred_prob))

    print(" ")







model LR
 
accuracy_score:  0.6751142857142857
confusion_matrix:  [[94516     0]
 [45484     0]]
precision_score:  0.0
recall_score:  0.0
f1_score:  0.0
roc_auc_score:  0.637926319447313
 


c:\Users\hp5cd\OneDrive\Desktop\Python\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])


model RF
 
accuracy_score:  0.6751142857142857
confusion_matrix:  [[94516     0]
 [45484     0]]
precision_score:  0.0
recall_score:  0.0
f1_score:  0.0
roc_auc_score:  0.637926319447313
 


c:\Users\hp5cd\OneDrive\Desktop\Python\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])


model XGB
 
accuracy_score:  0.6751142857142857
confusion_matrix:  [[94516     0]
 [45484     0]]
precision_score:  0.0
recall_score:  0.0
f1_score:  0.0
roc_auc_score:  0.637926319447313
 


c:\Users\hp5cd\OneDrive\Desktop\Python\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])


In [ ]:
# # pipeline  with single model
# # lr_source = Pipeline([('preprocessor',preprocessor1),('model',LogisticRegression(max_iter=1000))])
# # lr_source.fit(x1_train,y1_train)

# # prediction
# y1_pred = lr_source.predict(x1_test)

# y1_prob = lr_source.predict_proba(x1_test)[:,1]



# # classification metrices


# print(accuracy_score(y1_test,y1_pred))
# print(confusion_matrix(y1_test,y1_pred))
# print(precision_score(y1_test,y1_pred))
# print(recall_score(y1_test,y1_pred))
# print(f1_score(y1_test,y1_pred))
# print(roc_auc_score(y1_test,y1_prob))

In [ ]:
## checking why all 0 prediction

In [72]:

lead_conversion_data.groupby("lead_source")["converted"].mean()

lead_source
ads                 0.191567
app                 0.322659
indiamart           0.472543
interakt            0.239767
organic             0.208006
referral            0.491102
special_campaign    0.327589
website             0.423397
Name: converted, dtype: float64

In [73]:
print(y1_pred_prob[:20])

[0.32857773 0.47289687 0.23986147 0.1914254  0.1914254  0.3216173
 0.47289687 0.20666817 0.23986147 0.20666817 0.32857773 0.20666817
 0.32857773 0.1914254  0.42510074 0.1914254  0.3216173  0.47289687
 0.4913105  0.4913105 ]


In [74]:
pipeline.predict_proba(x1_test)[:10]

array([[0.67142224, 0.32857773],
       [0.5271031 , 0.47289687],
       [0.7601385 , 0.23986147],
       [0.8085746 , 0.1914254 ],
       [0.8085746 , 0.1914254 ],
       [0.6783827 , 0.3216173 ],
       [0.5271031 , 0.47289687],
       [0.79333186, 0.20666817],
       [0.7601385 , 0.23986147],
       [0.79333186, 0.20666817]], dtype=float32)

In [75]:
x1_train['lead_source'].value_counts(normalize=True)

lead_source
ads                 0.148138
organic             0.138257
special_campaign    0.132802
app                 0.132700
interakt            0.118261
referral            0.116437
indiamart           0.111946
website             0.101459
Name: proportion, dtype: float64

In [76]:
x1_test['lead_source'].value_counts(normalize=True)

lead_source
ads                 0.149300
organic             0.137129
special_campaign    0.132364
app                 0.130779
interakt            0.118693
referral            0.116250
indiamart           0.113086
website             0.102400
Name: proportion, dtype: float64

In [77]:
# changing the default prob to 0.35 from 0.5 and it works
# so we will optimize this and it can work slightly better

y_pred_new = (y1_pred_prob >= 0.35).astype(int)

print(confusion_matrix(y1_test, y_pred_new))
print(precision_score(y1_test, y_pred_new))
print(recall_score(y1_test, y_pred_new))
print(f1_score(y1_test, y_pred_new))

[[69484 25032]
 [24073 21411]]
0.4610167301853885
0.47073696244833346
0.46582614465826144


In [78]:
# SECOND MODEL

# preprocessing
preprocessor2 = ColumnTransformer(transformers=[('cat',OneHotEncoder(handle_unknown='ignore'),categorical_x2)])


# definind models to train
models2 = {'LR':LogisticRegression(max_iter=1000),
            'RF':RandomForestClassifier(n_estimators=20,max_depth=10,n_jobs=-1,random_state=42), 
            'XGB': XGBClassifier(n_estimators=50,max_depth=5,learning_rate=0.1,n_jobs=-1,random_state=42)}

for name2,model2 in models2.items():
    pipeline2 = Pipeline([('preprocessor',preprocessor2),
                          ('model',model2)])
    
    pipeline2.fit(x2_train,y2_train)

    y2_pred = pipeline2.predict(x2_test)
    y2_pred_prob = pipeline2.predict_proba(x2_test)[:,1]
    
    print("model", name2)

    print(" ")
    print("accuracy_score: ", accuracy_score(y2_test,y2_pred))
    print("confusion_matrix: ", confusion_matrix(y2_test,y2_pred))
    print("precision_score: ", precision_score(y2_test,y2_pred))
    print("recall_score: ", recall_score(y2_test,y2_pred))
    print("f1_score: ", f1_score(y2_test,y2_pred))
    print("roc_auc_score: ", roc_auc_score(y2_test,y2_pred_prob))

    print(" ")




model LR
 
accuracy_score:  0.6782785714285714
confusion_matrix:  [[91174  3342]
 [41699  3785]]
precision_score:  0.5310789953697208
recall_score:  0.08321607598276316
f1_score:  0.14388625952747525
roc_auc_score:  0.6448282738398113
 
model RF
 
accuracy_score:  0.6751285714285714
confusion_matrix:  [[94511     5]
 [45477     7]]
precision_score:  0.5833333333333334
recall_score:  0.00015390027262334008
f1_score:  0.0003077193599437313
roc_auc_score:  0.6416692683234371
 
model XGB
 
accuracy_score:  0.6768428571428572
confusion_matrix:  [[93483  1033]
 [44209  1275]]
precision_score:  0.5524263431542461
recall_score:  0.0280318353706798
f1_score:  0.05335621024439237
roc_auc_score:  0.6430556042132538
 


In [79]:
# changing the default prob to 0.35 from 0.5 and it works
# so we will optimize this and it can work slightly better

y2_pred_new = (y2_pred_prob >= 0.35).astype(int)

print(confusion_matrix(y2_test, y2_pred_new))
print(precision_score(y2_test, y2_pred_new))
print(recall_score(y2_test, y2_pred_new))
print(f1_score(y2_test, y2_pred_new))

[[68933 25583]
 [23692 21792]]
0.45998944591029023
0.47911353442968957
0.4693567667108196
